version: '3.8'

services:

  django:
    container_name: back-prod
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - .:/backend
    command: python manage.py runserver 127.0.0.1:8000

  vue-nginx:
    container_name: front-prod
    build: ./frontend/test-task
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - .:/frontend
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - django